import type {
  AlertItem,
  CrewMember,
  FeedbackReasonStat,
  FeedbackTrendPoint,
  ManagerCompany,
  ManagerUser,
  RecipeStat,
  Vessel,
  VesselDetail,
} from './types';

export const mockCompany: ManagerCompany = {
  id: 'company-demo',
  name: 'デモ船会社',
};

export const mockVessels: Vessel[] = [
  {
    id: 'vessel-sakura',
    name: '桜丸',
    imoNumber: 'IMO1234567',
    chefName: '田中 遼',
    crewSize: 24,
    status: 'ok',
    metrics: {
      responseRate: 0.84,
      positiveRate: 0.72,
      negativeRate: 0.11,
      changeRate: 0.06,
      lastUpdated: '2025-02-12T09:20:00Z',
      alerts: 1,
    },
    note: '新メニューの評判が安定。',
  },
  {
    id: 'vessel-hikari',
    name: '光丸',
    imoNumber: 'IMO7654321',
    chefName: '佐藤 航',
    crewSize: 31,
    status: 'warn',
    metrics: {
      responseRate: 0.68,
      positiveRate: 0.58,
      negativeRate: 0.19,
      changeRate: 0.14,
      lastUpdated: '2025-02-12T06:40:00Z',
      alerts: 3,
    },
    note: '辛味系の要望が増加。',
  },
  {
    id: 'vessel-tsubasa',
    name: '翼丸',
    imoNumber: 'IMO2468101',
    chefName: '中村 颯',
    crewSize: 18,
    status: 'critical',
    metrics: {
      responseRate: 0.52,
      positiveRate: 0.43,
      negativeRate: 0.29,
      changeRate: 0.23,
      lastUpdated: '2025-02-11T23:10:00Z',
      alerts: 5,
    },
    note: '献立変更が多く、回収率も低下。',
  },
  {
    id: 'vessel-minato',
    name: '港丸',
    imoNumber: 'IMO1357911',
    chefName: '鈴木 真央',
    crewSize: 27,
    status: 'ok',
    metrics: {
      responseRate: 0.78,
      positiveRate: 0.69,
      negativeRate: 0.12,
      changeRate: 0.08,
      lastUpdated: '2025-02-12T04:50:00Z',
      alerts: 0,
    },
    note: '回収率は安定。',
  },
];

export const mockAlerts: AlertItem[] = [
  {
    id: 'alert-001',
    vesselId: 'vessel-tsubasa',
    vesselName: '翼丸',
    type: 'response_drop',
    severity: 'high',
    createdAt: '2025-02-12T02:15:00Z',
    status: 'open',
    summary: '回答率が直近7日で-18pt',
    indicators: [
      { label: '回答率', value: '52% ( -18pt )' },
      { label: '未回収日', value: '3日連続' },
    ],
    reasons: ['乗組員のシフト変更', 'タブレット未設置'],
    recipes: ['鶏の照り焼き', '具だくさん味噌汁'],
  },
  {
    id: 'alert-002',
    vesselId: 'vessel-tsubasa',
    vesselName: '翼丸',
    type: 'negative_spike',
    severity: 'high',
    createdAt: '2025-02-11T19:05:00Z',
    status: 'open',
    summary: '不満率が急増 (+12pt)',
    indicators: [
      { label: '👎率', value: '29% ( +12pt )' },
      { label: '対象食', value: '夕食' },
    ],
    reasons: ['味が濃い', '量が少ない'],
    recipes: ['牛すじカレー', '青菜ソテー'],
  },
  {
    id: 'alert-003',
    vesselId: 'vessel-hikari',
    vesselName: '光丸',
    type: 'menu_change_spike',
    severity: 'medium',
    createdAt: '2025-02-11T11:30:00Z',
    status: 'open',
    summary: '当日変更率が14%に上昇',
    indicators: [
      { label: '変更率', value: '14% ( +6pt )' },
      { label: '変更理由', value: '食材不足' },
    ],
    reasons: ['冷凍在庫不足', '配送遅延'],
    recipes: ['白身魚のムニエル', '豆乳スープ'],
  },
  {
    id: 'alert-004',
    vesselId: 'vessel-hikari',
    vesselName: '光丸',
    type: 'negative_spike',
    severity: 'medium',
    createdAt: '2025-02-10T08:20:00Z',
    status: 'done',
    summary: '不満率が8pt上昇 (対応済み)',
    indicators: [
      { label: '👎率', value: '19% ( +8pt )' },
      { label: '対象食', value: '昼食' },
    ],
    reasons: ['味が薄い'],
    recipes: ['鯖の塩焼き'],
  },
  {
    id: 'alert-005',
    vesselId: 'vessel-sakura',
    vesselName: '桜丸',
    type: 'menu_change_spike',
    severity: 'low',
    createdAt: '2025-02-09T09:10:00Z',
    status: 'open',
    summary: '当日変更率が6%で注意',
    indicators: [
      { label: '変更率', value: '6% ( +2pt )' },
      { label: '対象食', value: '朝食' },
    ],
    reasons: ['食材入荷遅れ'],
    recipes: ['オムレツ'],
  },
];

export const mockTrend: FeedbackTrendPoint[] = [
  { date: '02/06', positiveRate: 0.68, negativeRate: 0.15, responseRate: 0.76 },
  { date: '02/07', positiveRate: 0.7, negativeRate: 0.14, responseRate: 0.78 },
  { date: '02/08', positiveRate: 0.66, negativeRate: 0.18, responseRate: 0.74 },
  { date: '02/09', positiveRate: 0.71, negativeRate: 0.12, responseRate: 0.8 },
  { date: '02/10', positiveRate: 0.69, negativeRate: 0.16, responseRate: 0.77 },
  { date: '02/11', positiveRate: 0.63, negativeRate: 0.2, responseRate: 0.7 },
  { date: '02/12', positiveRate: 0.67, negativeRate: 0.17, responseRate: 0.73 },
];

const baseReasons: FeedbackReasonStat[] = [
  { reason: '味が濃い', rate: 0.23, count: 42 },
  { reason: '量が少ない', rate: 0.18, count: 33 },
  { reason: '献立が偏る', rate: 0.15, count: 28 },
  { reason: '味が薄い', rate: 0.13, count: 24 },
  { reason: '野菜不足', rate: 0.11, count: 20 },
];

const baseRecipes: RecipeStat[] = [
  { id: 'recipe-001', name: '牛すじカレー', positiveRate: 0.52, negativeRate: 0.31, responses: 48 },
  { id: 'recipe-002', name: '白身魚のムニエル', positiveRate: 0.58, negativeRate: 0.24, responses: 44 },
  { id: 'recipe-003', name: '鶏の照り焼き', positiveRate: 0.79, negativeRate: 0.09, responses: 62 },
  { id: 'recipe-004', name: '豆乳スープ', positiveRate: 0.66, negativeRate: 0.17, responses: 39 },
  { id: 'recipe-005', name: 'チキン南蛮', positiveRate: 0.82, negativeRate: 0.07, responses: 55 },
  { id: 'recipe-006', name: '鯖の塩焼き', positiveRate: 0.6, negativeRate: 0.21, responses: 46 },
];

export const mockVesselDetails: Record<string, VesselDetail> = {
  'vessel-sakura': {
    vessel: mockVessels[0],
    reasons: baseReasons.slice(0, 4),
    recipes: baseRecipes.slice(0, 4),
    notes: '和食中心の構成が高評価。',
  },
  'vessel-hikari': {
    vessel: mockVessels[1],
    reasons: [
      { reason: '味が薄い', rate: 0.21, count: 18 },
      { reason: '辛さ不足', rate: 0.19, count: 16 },
      { reason: '量が少ない', rate: 0.16, count: 14 },
      { reason: '脂っこい', rate: 0.12, count: 10 },
      { reason: '献立が単調', rate: 0.11, count: 9 },
    ],
    recipes: [
      { id: 'recipe-010', name: '麻婆豆腐', positiveRate: 0.48, negativeRate: 0.3, responses: 32 },
      { id: 'recipe-011', name: '鶏の照り焼き', positiveRate: 0.74, negativeRate: 0.12, responses: 41 },
      { id: 'recipe-012', name: '味噌ラーメン', positiveRate: 0.61, negativeRate: 0.19, responses: 37 },
      { id: 'recipe-013', name: '鮭の塩麹焼き', positiveRate: 0.69, negativeRate: 0.15, responses: 29 },
      { id: 'recipe-014', name: 'きんぴらごぼう', positiveRate: 0.58, negativeRate: 0.17, responses: 24 },
    ],
    notes: '辛味調整の要望が多い。',
  },
  'vessel-tsubasa': {
    vessel: mockVessels[2],
    reasons: [
      { reason: '量が少ない', rate: 0.28, count: 22 },
      { reason: '味が濃い', rate: 0.24, count: 19 },
      { reason: '食材が固い', rate: 0.2, count: 16 },
      { reason: '野菜不足', rate: 0.16, count: 12 },
      { reason: '献立が偏る', rate: 0.12, count: 9 },
    ],
    recipes: [
      { id: 'recipe-020', name: '牛すじカレー', positiveRate: 0.44, negativeRate: 0.34, responses: 28 },
      { id: 'recipe-021', name: '豚生姜焼き', positiveRate: 0.56, negativeRate: 0.27, responses: 26 },
      { id: 'recipe-022', name: '白身魚のムニエル', positiveRate: 0.49, negativeRate: 0.29, responses: 21 },
      { id: 'recipe-023', name: '春雨サラダ', positiveRate: 0.62, negativeRate: 0.18, responses: 18 },
      { id: 'recipe-024', name: '回鍋肉', positiveRate: 0.51, negativeRate: 0.31, responses: 25 },
    ],
    notes: '調達遅延の影響で献立変更が頻発。',
  },
  'vessel-minato': {
    vessel: mockVessels[3],
    reasons: baseReasons,
    recipes: baseRecipes,
    notes: 'フィードバック回収率は高水準。',
  },
};

export const mockCrew: CrewMember[] = [
  {
    id: 'crew-001',
    vesselId: 'vessel-sakura',
    alias: 'Crew-001',
    cardBound: true,
    cardUid: 'NFC-23A8',
    dietFlags: ['甲殻類NG', '減塩'],
    spiceTolerance: 'low',
    saltPreference: 'low',
  },
  {
    id: 'crew-002',
    vesselId: 'vessel-sakura',
    alias: 'Crew-002',
    cardBound: false,
    dietFlags: ['宗教: 豚肉NG'],
    spiceTolerance: 'mid',
    saltPreference: 'normal',
  },
  {
    id: 'crew-003',
    vesselId: 'vessel-hikari',
    alias: 'Crew-014',
    cardBound: true,
    cardUid: 'NFC-81K2',
    dietFlags: ['卵NG'],
    spiceTolerance: 'low',
    saltPreference: 'normal',
  },
  {
    id: 'crew-004',
    vesselId: 'vessel-hikari',
    alias: 'Crew-018',
    cardBound: true,
    cardUid: 'NFC-9T55',
    dietFlags: ['辛味控えめ'],
    spiceTolerance: 'low',
    saltPreference: 'normal',
  },
  {
    id: 'crew-005',
    vesselId: 'vessel-tsubasa',
    alias: 'Crew-031',
    cardBound: false,
    dietFlags: ['乳製品NG'],
    spiceTolerance: 'mid',
    saltPreference: 'low',
  },
  {
    id: 'crew-006',
    vesselId: 'vessel-minato',
    alias: 'Crew-007',
    cardBound: true,
    cardUid: 'NFC-45P1',
    dietFlags: [],
    spiceTolerance: 'high',
    saltPreference: 'normal',
  },
];

export const mockUsers: ManagerUser[] = [
  {
    id: 'user-001',
    name: '佐藤 航',
    email: 'sato.chef@example.com',
    role: 'CHEF',
    vessels: ['vessel-hikari'],
    status: 'active',
  },
  {
    id: 'user-002',
    name: '田中 遼',
    email: 'tanaka.chef@example.com',
    role: 'CHEF',
    vessels: ['vessel-sakura'],
    status: 'active',
  },
  {
    id: 'user-003',
    name: '中村 颯',
    email: 'nakamura.chef@example.com',
    role: 'CHEF',
    vessels: ['vessel-tsubasa'],
    status: 'invited',
  },
  {
    id: 'user-004',
    name: '本部担当 早川',
    email: 'hayakawa.manager@example.com',
    role: 'MANAGER',
    vessels: ['vessel-sakura', 'vessel-hikari', 'vessel-tsubasa', 'vessel-minato'],
    status: 'active',
  },
];

export const mockFeedbackReasons = baseReasons;
export const mockRecipeStats = baseRecipes;
